# -*- coding: utf-8 -*-
"""Ai_Chatbot_in_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yI3UO37YIi-fsAf0EXeekGmGPONgzz39

## Ai Chatbot
"""

pip install chatterbot

pip install chatterbot_corpus

def create_bot(name):
    from chatterbot import ChatBot
    Bot = ChatBot(name = name,
                  read_only = False,                  
                  logic_adapters = ["chatterbot.logic.BestMatch"],                 
                  storage_adapter = "chatterbot.storage.SQLStorageAdapter")
    return Bot

def train_all_data(Bot):
    from chatterbot.trainers import ChatterBotCorpusTrainer
    corpus_trainer = ChatterBotCorpusTrainer(Bot)
    corpus_trainer.train("chatterbot.corpus.english")


def custom_train(Bot, conversation):
    from chatterbot.trainers import ListTrainer
    trainer = ListTrainer(Bot)
    trainer.train(conversation)


def start_chatbot(Bot):
    print('\033c')
    print("Hello, I am Jordan. How can I help you")
    bye_list = ["bye jordan", "bye", "good bye"] 
    
    while (True):
        user_input = input("me: ")   
        if user_input.lower() in bye_list:
            print("Jordan: Good bye and have a Nice day")
            break
        
        response = Bot.get_response(user_input)
        print("Jordan:", response)

bot = create_bot('Jordan')


train_all_data(bot)


my_owner = [
    "Who made you?",
    "Manoj Prajapati"
]

custom_train(bot, my_owner)


start_chatbot(bot)